WIP
openshift/image-registry pull request #258
Opened 2020-12-01 10:12 UTC by dmage

2020-12-03 12:07 UTC, ricardomaraschini requested changes

2020-12-03 12:07 UTC, ricardomaraschini commented on test/integration/pullthrough/pullthrough_test.go
> +	remoteRegistryAddr, _, _ := testframework.CreateEphemeralRegistry(t, master.AdminKubeConfig(), namespace, nil)
see my previous comment on "cleaners" being ignored.

2020-12-03 13:22 UTC, dmage commented on test/integration/metricspullthrough/metricspullthrough_test.go
> +	remoteRegistryAddr, _, _ := testframework.CreateEphemeralRegistry(t, master.AdminKubeConfig(), testproject.Name, map[string]string{
only one test needs to delete the ephemeral registry in the middle of the test, other tests can rely on namespace deletion

2020-12-03 13:28 UTC, dmage commented on test/integration/metricspullthrough/metricspullthrough_test.go
> +	}
it always exists, in worst case the next step will fail

2020-12-04 09:04 UTC, ricardomaraschini approved these changes
/lgtm

2020-12-04 11:42 UTC, merged

2021-02-19 15:33 UTC, dmage commented
/cherrypick release-4.6