WIP - Image registry ICSP support
openshift/image-registry pull request #267
Opened 2021-03-09 10:05 UTC by ricardomaraschini

2021-03-17 20:27 UTC, ricardomaraschini commented
/retest

2021-03-18 06:05 UTC, ricardomaraschini commented
/retest

2021-03-18 08:17 UTC, ricardomaraschini commented
/retest

2021-03-18 08:45 UTC, ricardomaraschini commented
/assign @dmage

2021-03-18 08:46 UTC, ricardomaraschini commented
@dmage Even though we still don't have a definitive version for https://github.com/openshift/library-go/pull/939 it might be good to start reviewing this.

2021-03-19 14:58 UTC, dmage requested changes

2021-03-19 14:58 UTC, dmage commented on pkg/dockerregistry/server/util.go
> +		strategy.NewSimpleLookupICSPStrategy("", icsp),
This strategy shouldn't be used by the registry. The registry shouldn't ask api-server for a list for ICSPs on every incoming request, it should use informers that use watches to update their cache.

2021-04-08 08:40 UTC, xiuwang commented
Need to launch a disconnect cluster which is blocked by qe jenkins job outage.

2021-04-08 13:27 UTC, dmage commented
@xiuwang please don't test WIP (work-in-progress) PRs

2021-06-07 08:46 UTC, ricardomaraschini commented
Closing this one as there is a new PR to add ICSP support: https://github.com/openshift/image-registry/pull/277

2021-06-07 08:46 UTC, closed without merging